version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai
    environment:
      POSTGRES_USER: finance-ai
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: finance-ai-db
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data

volumes:
  .postgres:
